#!/bin/bash

chown jenkins /var/jenkins_home
if [ ! -e "/var/jenkins_home/config.xml" ] ; then
  cp -r /var/jenkins_home_templates/* /var/jenkins_home/

  mkdir -p /var/jenkins_home/plugins
  cd /var/jenkins_home/plugins
  cp /var/plugins/* .
  chown -R jenkins /var/jenkins_home
fi

su - jenkins -c "JENKINS_HOME=$JENKINS_HOME /usr/bin/java -jar /usr/share/jenkins/jenkins.war"
